export const FETCH_TWITS = "FETCH_TWITS";
export const FETCH_TWITS_FULFILLED = "FETCH_TWITS_FULFILLED";
export const FETCH_TWITS_REJECTED = "FETCH_TWITS_REJECTED";

export const TWITS_FILTERS_CHANGED = "TWITS_FILTERS_CHANGED";
